### ISSUE TITLE
logger.warning('the link you followed is private or not a page: ',

### ISSUE THREAD

**Issue by elcoloo** [wael-sudo2/facebook-page-info-scraper#26]
I'm getting this error with some URLs but the page is not private, it's a page

---------------------------------
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/colo/old-scripts/fb.py", line 15, in <module>
    page_info = scraper.get_page_info()
  File "/home/colo/.local/lib/python3.10/site-packages/facebook_page_info_scraper/facebook_page_info_scraper.py", line 478, in get_page_info
    return self.fetch_functions()
  File "/home/colo/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/colo/.local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/colo/.local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/colo/.local/lib/python3.10/site-packages/facebook_page_info_scraper/facebook_page_info_scraper.py", line 473, in fetch_functions
    logger.warning('the link you followed is private or not a page: ',
Message: 'the link you followed is private or not a page: '
Arguments: ('https://www.facebook.com/alexpoffisiell/about',)
Details for https://www.facebook.com/alexpoffisiell:

**Comment by wael-sudo2** [comment]
try passing the argument as Arguments: 'https://www.facebook.com/alexpoffisiell' 
and use the latest version 1.1.2 and your problem should be fixed
